const orders = [
  {
    id: "o1",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o2",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o3",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o4",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o5",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o6",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o7",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
  {
    id: "o8",
    date: "",
    products: [],
    description: "",
    is_verfied_up: true,
    is_picked_up: true,
    is_dropped_off: false,
    order_delivered: false,
  },
];

export default products;
